### ISSUE TITLE
MAT Loggers failing on first connection, every time

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#10]
When connecting to a MATP-2W Logger, the connection fails on the first attempt, every time.  Upon retry it works.  This is true even at close range.

**Comment by kazola** [comment]
please recall we did MAT loggers on bluepy as experimental, then on DDH as experimental, theoretically, this is hugely fixed in MAT lib v3 with a time.sleep(1) but, to be fair, some times it still happens, I think because old RN4020 on MAT loggers

**Comment by Nickel33** [comment]
Fixed.
