### ISSUE TITLE
DDH crashes on start up... on some units

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#11]
The DDH software is crashing on startup on some units.  I have four, new DDH with identically clones SSDs.  When the DDH software starts, two of them run normally.  But two crash after the GPS acquires its position.

**Comment by kazola** [comment]
raspberry cloning error, we tried to do from rpi3 to rpi4 directly, we cannot --> fixed with new installation from scratch

**Comment by kazola** [comment]
should be fixed, please test @Nickel33

**Comment by Nickel33** [comment]
Fixed.  Cloning issue.
