### ISSUE TITLE
Check math on depth calculation for Moana and MAT Loggers

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#14]

**Comment by kazola** [comment]
The pressure in dbar and the depth in meters are approximately equal, so the pressure in the ocean at 1 m depth is approximately 1 dbar, and that at 1000 m approximately 1000 dbar...

Bottom line: I would not change anything here

**Comment by Nickel33** [comment]
Moana looks correct. But MATP loggers are not correct.  Moana reports pressure excluding atmospheric pressure (gauge pressure). MATP reports pressure including atmospheric pressure.  Therefore, to convert MATP pressure first subtract atmospheric pressure.  We don't have a barometer, so we will need to use a fixed value of 10.1 dBar.

**Comment by kazola** [comment]
Solved in this in file ddh_utils, function lid_to_csv

**Comment by Nickel33** [comment]
Looks good. Closing.
