### ISSUE TITLE
Depth is reported in Decibars in plot window, not meters/fathoms

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#3]
In the plot window, the depth (m) is really decibars.  It should be in either meters or fathoms.

**Comment by kazola** [comment]
this was working properly for DO loggers, not for MAT --> enhanced and fixed in DDH v3

**Comment by kazola** [comment]
I realize I don't understand this issue.
So, please check @Nickel33. If still not doing what expected, please reassign to me, it will be an easy fix changing plot labels.

**Comment by Nickel33** [comment]
Done. But need to check the math.  Closing.
