### ISSUE TITLE
Add screensaver/fully dimmable display

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#5]
Story:  Customers are using the DDH at night in a dark wheelhouse.  Even when dimmed, the display is too bright and blinding.

Discussion: Can we give the option to turn it down even more and/or use a screen saver (starry sky) that  is mostly dark?  Or maybe the display can be turned off and activated again by touching the screen?

**Comment by kazola** [comment]
in progress, remove need for root from DDH

**Comment by Nickel33** [comment]
Added with percentages.
