### ISSUE TITLE
"RN4020 Deployed" message is unclear in History

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#6]
Story:  As a user, when viewing the History Tab, I have no idea what "RN4020 Deployed" means.

Discussion:  Maybe it should just say: "Offloaded and Restarted".
What are the other possible messages?  We should make sure they are all easy to understand.

**Comment by kazola** [comment]
this was because MAT / RN4020 loggers support in DDH was experimental
should be fixed in last DDH v3 version

**Comment by kazola** [comment]
this no longer happens, we changed the way we display messages
