### ISSUE TITLE
Change time to GMT on data file

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#7]
Story: NMFS would like the data file times to be GMT.  This helps them keep data synchronized across multiple regions and products.

Discussion:  The fishermen would probably want to see the local time on the display.  But should the loggers be set to GMT?  Or should everything be set to GMT?

**Comment by kazola** [comment]
I don't recommend changing the firmware to do this, C++ code for timezones it's a nightname to debug, let's do it in MAT library / python

**Comment by Nickel33** [comment]
Fixed.
