### ISSUE TITLE
Alert the user if there are no assigned loggers

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#7]
Story:  A user gets a  DDH and starts using it.  Unknown to them, the box has not been configured with an assigned logger. The DDH says it its "searching for loggers", but it isn't really, since it has no assigned loggers.  The user does not know that it is not them, rather the DDH was not properly configured.

Fixed:  When there are no assigned loggers, display a message that says, "Need Logger Assignment" and don't show the RF icon.

**Comment by kazola** [comment]
done
