### ISSUE TITLE
Add plot view option to  display "last haul" for trawlers

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/ddh#8]
Story:  As a trawler captain, I am making decisions about water temperature from haul to haul. I am not interested in the water temperature history beyond the most recent haul.  So I want to see the data from the most recent haul, not a specific time frame. If I trawl for 45 minutes, I want to see 45 minutes.  If I trawl for 4 hours, I want to see all four hours.

Discussion:  This is a change from the way that fixed gear fishermen are operating.  The DDH might need to have two fishing modes.  Mobile gear (nets) and fixed gear (traps).

**Comment by kazola** [comment]
in progress

**Comment by kazola** [comment]
done, you need to change the DDH mode in ddh.json file manually or by means of the hidden configuration tab
the type plot is indicated in the plot title, once it appears
please test @Nickel33

**Comment by Nickel33** [comment]
Added, but more data points displayed would be better.  Closing. Will create a new issue for more points.
